function model_file = build_geometry_simulink_model()
%BUILD_GEOMETRY_SIMULINK_MODEL Rebuild an owned model using standard blocks.
% The user explicitly requested this portable programmatic build script.
% Unknown or unsaved existing models are never overwritten.
cfg=checkpoint_setup(); mdl=cfg.model;
marker='blackice_checkpoint01_generated';
if bdIsLoaded(mdl)
    assert(strcmp(get_param(mdl,'Dirty'),'off'), ...
        'blackice:UnsavedModel','Save/close existing edits before rebuilding.');
    assert(contains(get_param(mdl,'Description'),marker), ...
        'blackice:UnownedModel','Existing model is not checkpoint-owned.');
elseif isfile(cfg.model_file)
    load_system(cfg.model_file);
    assert(contains(get_param(mdl,'Description'),marker), ...
        'blackice:UnownedModel','Existing model is not checkpoint-owned.');
else
    new_system(mdl);
end
% Reuse the owned diagram on reruns to avoid new_system shadowing its own
% saved .slx on the MATLAB path. Only generated top-level blocks are reset.
Simulink.BlockDiagram.deleteContents(mdl);
set_param(mdl,'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
    'FixedStep','1','StartTime','0','StopTime','0','SaveOutput','on', ...
    'OutputSaveName','yout','SaveFormat','Dataset','ReturnWorkspaceOutputs','on', ...
    'SaveTime','on','TimeSaveName','tout','Description',marker);
mw=get_param(mdl,'ModelWorkspace');
assignin(mw,'H_m',cfg.pilot_H_m); assignin(mw,'t_m',0.030);
assignin(mw,'theta_deg',0);
src=cell(1,3);
names={'H_m','t_m','theta_deg'};
for k=1:3
    src{k}=[mdl '/' names{k}];
    add_block('simulink/Sources/Constant',src{k},'Value',names{k}, ...
        'Position',[35 65+95*(k-1) 120 100+95*(k-1)]);
end
valid=[mdl '/GeometryValidity']; ideal=[mdl '/IdealRanges'];
add_block('built-in/Subsystem',valid,'Position',[205 45 375 190]);
add_block('built-in/Subsystem',ideal,'Position',[460 70 660 275]);
buildValidity(valid);
buildRanges(ideal);
for k=1:3
    add_line(mdl,[names{k} '/1'],['GeometryValidity/' num2str(k)],'autorouting','on');
    add_line(mdl,[names{k} '/1'],['IdealRanges/' num2str(k)],'autorouting','on');
end
add_line(mdl,'GeometryValidity/1','IdealRanges/4','autorouting','on');
outnames={'D_A','D_I','DeltaD_geo','geometry_valid'};
for k=1:4
    add_block('simulink/Sinks/Out1',[mdl '/' outnames{k}],'Port',num2str(k), ...
        'Position',[760 80+65*(k-1) 800 100+65*(k-1)]);
    if k<4
        add_line(mdl,['IdealRanges/' num2str(k)],[outnames{k} '/1'],'autorouting','on');
    else
        add_line(mdl,'GeometryValidity/1',[outnames{k} '/1'],'autorouting','on');
    end
end
set_param(mdl,'Description',[marker ': Level 0 simulation-only; theta from road normal; ' ...
    'DA=H/cos(theta), DI=(H-t)/cos(theta). Invalid ranges are NaN. ' ...
    'Generated by build_geometry_simulink_model.']);
save_system(mdl,cfg.model_file);
open_system(mdl);
model_file=cfg.model_file;
fprintf('Built standard-block geometry model: %s\n',model_file);
end

function buildValidity(s)
for k=1:3
    add_block('simulink/Sources/In1',[s '/u' num2str(k)],'Port',num2str(k), ...
        'Position',[20 60+95*(k-1) 50 80+95*(k-1)]);
end
add_block('simulink/Sources/Constant',[s '/Zero'],'Value','0','Position',[95 380 125 400]);
add_block('simulink/Sources/Constant',[s '/Ninety'],'Value','90','Position',[95 430 125 450]);
add_block('simulink/Sources/Constant',[s '/Infinity'],'Value','Inf','Position',[95 480 125 500]);
ops={'>','>=','>=','<'}; bn={'HeightAboveIce','ThicknessNonnegative','AngleNonnegative','AngleBelow90'};
left={'u1/1','u2/1','u3/1','u3/1'}; right={'u2/1','Zero/1','Zero/1','Ninety/1'};
for k=1:4
    add_block('simulink/Logic and Bit Operations/Relational Operator',[s '/' bn{k}], ...
        'Operator',ops{k},'Position',[245 25+65*(k-1) 295 55+65*(k-1)]);
    add_line(s,left{k},[bn{k} '/1'],'autorouting','on');
    add_line(s,right{k},[bn{k} '/2'],'autorouting','on');
end
for k=1:3
    absname=['Abs' num2str(k)]; finname=['Finite' num2str(k)];
    add_block('simulink/Math Operations/Abs',[s '/' absname], ...
        'Position',[165 305+65*(k-1) 200 330+65*(k-1)]);
    add_block('simulink/Logic and Bit Operations/Relational Operator',[s '/' finname], ...
        'Operator','<','Position',[245 300+65*(k-1) 295 335+65*(k-1)]);
    add_line(s,['u' num2str(k) '/1'],[absname '/1'],'autorouting','on');
    add_line(s,[absname '/1'],[finname '/1'],'autorouting','on');
    add_line(s,'Infinity/1',[finname '/2'],'autorouting','on');
end
add_block('simulink/Logic and Bit Operations/Logical Operator',[s '/AllConditions'], ...
    'Operator','AND','Inputs','7','Position',[410 110 465 365]);
for k=1:4, add_line(s,[bn{k} '/1'],['AllConditions/' num2str(k)],'autorouting','on'); end
for k=1:3, add_line(s,['Finite' num2str(k) '/1'],['AllConditions/' num2str(k+4)],'autorouting','on'); end
add_block('simulink/Sinks/Out1',[s '/valid'],'Position',[540 220 570 240]);
add_line(s,'AllConditions/1','valid/1');
end

function buildRanges(s)
for k=1:4
    add_block('simulink/Sources/In1',[s '/u' num2str(k)],'Port',num2str(k), ...
        'Position',[20 40+85*(k-1) 50 60+85*(k-1)]);
end
add_block('simulink/Math Operations/Gain',[s '/DegreesToRadians'],'Gain','pi/180', ...
    'Position',[110 205 180 235]);
add_block('simulink/Math Operations/Trigonometric Function',[s '/Cosine'], ...
    'Operator','cos','Position',[225 205 265 235]);
add_block('simulink/Sources/Constant',[s '/One'],'Value','1','Position',[225 340 255 360]);
add_block('simulink/Signal Routing/Switch',[s '/SafeDenominator'], ...
    'Criteria','u2 ~= 0','Position',[310 215 355 285]);
add_line(s,'u3/1','DegreesToRadians/1'); add_line(s,'DegreesToRadians/1','Cosine/1');
add_line(s,'Cosine/1','SafeDenominator/1','autorouting','on');
add_line(s,'u4/1','SafeDenominator/2','autorouting','on');
add_line(s,'One/1','SafeDenominator/3','autorouting','on');
add_block('simulink/Math Operations/Sum',[s '/HeightMinusThickness'], ...
    'Inputs','+-','Position',[150 105 185 145]);
add_line(s,'u1/1','HeightMinusThickness/1','autorouting','on');
add_line(s,'u2/1','HeightMinusThickness/2','autorouting','on');
for k=1:2
    add_block('simulink/Math Operations/Divide',[s '/Divide' num2str(k)], ...
        'Position',[415 40+95*(k-1) 455 75+95*(k-1)]);
    add_line(s,'SafeDenominator/1',['Divide' num2str(k) '/2'],'autorouting','on');
end
add_line(s,'u1/1','Divide1/1','autorouting','on');
add_line(s,'HeightMinusThickness/1','Divide2/1','autorouting','on');
add_block('simulink/Math Operations/Sum',[s '/RangeDifference'], ...
    'Inputs','+-','Position',[525 225 560 265]);
add_line(s,'Divide1/1','RangeDifference/1','autorouting','on');
add_line(s,'Divide2/1','RangeDifference/2','autorouting','on');
add_block('simulink/Sources/Constant',[s '/InvalidRange'],'Value','NaN','Position',[500 365 545 390]);
sources={'Divide1','Divide2','RangeDifference'};
for k=1:3
    mask=['Mask' num2str(k)]; outname=['y' num2str(k)];
    add_block('simulink/Signal Routing/Switch',[s '/' mask], ...
        'Criteria','u2 ~= 0','Position',[635 35+100*(k-1) 675 100+100*(k-1)]);
    add_line(s,[sources{k} '/1'],[mask '/1'],'autorouting','on');
    add_line(s,'u4/1',[mask '/2'],'autorouting','on');
    add_line(s,'InvalidRange/1',[mask '/3'],'autorouting','on');
    add_block('simulink/Sinks/Out1',[s '/' outname],'Port',num2str(k), ...
        'Position',[750 55+100*(k-1) 780 75+100*(k-1)]);
    add_line(s,[mask '/1'],[outname '/1']);
end
end
