function c = level2_parameters()
%LEVEL2_PARAMETERS Predeclared stress protocol; no calibrated sensor values.
c=simulation_parameters();
c.protocol='checkpoint02_stress_v1';
c.D_ref_m=1.6;
c.N_candidates=[1000 5000 10000];
c.max_unconditional_CI_width=.03; % 95% worst-case Wilson full width.
c.reference_modes=["R0" "R1"]; % Shared-offset R2 is deferred.
c.stream_offset=100000;
c.figure_H_m=1.5; c.figure_sigma_mm=10; c.figure_t_mm=10;
c.figure_angle_deg=30; c.figure_pfa=.05;
c.families=table(["L1";repmat("L2-A",3,1);repmat("L2-B",3,1);repmat("L2-C",3,1)], ...
 ["baseline";repmat(["mild";"moderate";"severe"],3,1)], ...
 [0;.5;1;2;0;0;0;.5;1;2],[0;0;0;0;.5;1;2;.5;1;2], ...
 'VariableNames',{'family','severity','p','q'});
% V1 limits and V2 coefficients are hypothetical, fixed before simulation.
c.validities=table(["V0";repmat("V1",3,1);repmat("V2",3,1)], ...
 ["all";repmat(["mild";"moderate";"severe"],2,1)], ...
 [Inf;70;60;50;Inf;Inf;Inf],[Inf;8;5;3;Inf;Inf;Inf], ...
 [0;0;0;0;.15;.5;1.5], ...
 'VariableNames',{'mode','severity','theta_max_deg','D_max_m','lambda'});
end
